/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

import db.DBWorker;


public class LoginForm extends javax.swing.JFrame {
	
	private static LoginForm instance;
	
	public static synchronized LoginForm getInstance(){
		if(instance == null){
			instance = new LoginForm();
		}
		return instance;
	}

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setVisible(true);
    }

    private boolean validateData() {
        String loginName = loginField.getText();
        String password = passwordField.getText();

        boolean valid = true;
       
        if (loginName.isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Поле логiну пусте. Заповнiть його.",
                    "Помилка",
                    JOptionPane.ERROR_MESSAGE);
            valid = false;
        }
        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Поле паролю пусте. Заповнiть його.",
                    "Помилка",
                    JOptionPane.ERROR_MESSAGE);
            valid = false;
        }
        
        return valid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Вікно авторизації");

        jLabel1.setText("Введіть свій логін:");

        jLabel2.setText("Введіть пароль");

        loginButton.setText("Увійти");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginField, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(passwordField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(loginButton)
                        .addGap(0, 150, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(loginButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String loginName = loginField.getText();
        String password = passwordField.getText();

        if (validateData()) {
            try {
                DBWorker con = DBWorker.getInstance();

                String query = "SELECT login,password FROM user;";
                Statement stmt = con.getConnection().createStatement();
                ResultSet rs = stmt.executeQuery(query);
                boolean validatePass = false;
                
                
                while (rs.next()) {
                    String login = rs.getString(1);
                    String pass = rs.getString(2);
                    
                    System.out.println(pass);
                    System.out.println(md5Digest(password));
                    
                    validatePass |= login.equals(loginName) && pass.equals(md5Digest(password));
                }
                
                if (validatePass) {
                    MainFrame.getInstance().setVisible(true);
                    setVisible(false);
                    validateData();
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Невiрний пароль. Спробуйте ще.",
                            "Помилка",
                            JOptionPane.ERROR_MESSAGE);
                    
                }

                stmt.close();

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        revalidate();
    }//GEN-LAST:event_loginButtonActionPerformed
    
    
    private String md5Digest(String original) {
        MessageDigest md;
        try {
            md = MessageDigest.getInstance("MD5");
             md.update(original.getBytes());
        byte[] digest = md.digest();
        StringBuilder sb = new StringBuilder();
        for (byte b : digest) {
            sb.append(String.format("%02x", b & 0xff));
        }
        return sb.toString();
        } catch (NoSuchAlgorithmException ex) {
            //do nothing
        }
       return null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginField;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
